<?php

$title = 'Lista de Livros';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('livro', array('action'=>'add'));?>"><button type="button" class="btn btn-default btn-sm">Adicionar Livro</button></a>
</p>

<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Autor</th>
            <th>Editora</th>
            <th>Título da Obra</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($livros as $livro) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($livro->id);?></td>
            <td><?php echo $this->escapeHtml($livro->autor);?></td>
            <td><?php echo $this->escapeHtml($livro->editora);?></td>
            <td><?php echo $this->escapeHtml($livro->titulo);?></td>
            <td>
                <a href="<?php echo $this->url('livro',
                    array('action'=>'edit', 'id' => $livro->id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    &nbsp;&nbsp;
                <a href="<?php echo $this->url('livro',
                    array('action'=>'delete', 'id' => $livro->id));?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    &nbsp;&nbsp;
                <a href="#" onclick="verLivro(<?=$livro->id?>)"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<!-- Modal ver livro-->
<div class="modal fade bs-example-modal-sm" id="modalVerLivro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Visualizar Livro</h4>
      </div>
      <div class="modal-body" id="conteudoModal">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>