
<table class="table">
    <tr>
        <td>ID</td>
        <td><?php echo $this->escapeHtml($livros->id);?></td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td><?php echo $this->escapeHtml($livros->titulo);?></td>
    </tr>
    <tr>
        <td>Autor</td>
        <td><?php echo $this->escapeHtml($livros->autor);?></td>
    </tr>
    <tr>
        <td>Editora</td>
        <td><?php echo $this->escapeHtml($livros->editora);?></td>
    </tr>
    <tr>
        <td>Data Cadastro</td>
        <td><?php echo $this->escapeHtml(date('d/m/Y', strtotime($livros->dataCadastro)));?></td>
    </tr>
    <tr>
        <td>Valor</td>
        <td><?php echo $this->escapeHtml($livros->valor);?></td>
    </tr>
    <tr>
        <td>Observações</td>
        <td><?php echo $this->escapeHtml($livros->obs);?></td>
    </tr>
</table>
