<?php

$title = 'Deletar Livro';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Confirmar a exclusão do livro
    '<?php echo $this->escapeHtml($livro->titulo); ?>' -
    '<?php echo $this->escapeHtml($livro->autor); ?>'?
</p>
<?php
$url = $this->url('livro', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $livro->id; ?>" />
    <input type="submit" name="del" value="Sim" />
    <input type="submit" name="del" value="Não" />
</div>
</form>