<?php

$title = 'Relatório de Devedores';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('emprestimo', array('action'=>'add'));?>"><button type="button" class="btn btn-default btn-sm">Adicionar Emprestimo</button></a>
</p>

<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Cliente</th>
            <th>Título da Obra</th>
            <th>Data de Devolução</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($emprestimos as $emprestimo) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($emprestimo->cliente);?></td>
            <td><?php echo $this->escapeHtml($emprestimo->titulo);?></td>
            <td><?php echo $this->escapeHtml(date('d/m/Y', strtotime($emprestimo->dataEmprestimo)));?></td>
            <td>
                <a href="<?php echo $this->url('emprestimo',
                    array('action'=>'edit', 'id' => $emprestimo->id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    &nbsp;&nbsp;
                <a href="<?php echo $this->url('emprestimo',
                    array('action'=>'delete', 'id' => $emprestimo->id));?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
