<?php

$title = 'Cadastro de Cliente';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cliente', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <label><?php echo $form->get('cliente')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('cliente')); ?>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label><?php echo $form->get('dataNascimento')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('dataNascimento')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <label><?php echo $form->get('endereco')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('endereco')); ?>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label><?php echo $form->get('cpf')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('cpf')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <label><?php echo $form->get('email')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('email')); ?>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label><?php echo $form->get('telefone')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('telefone')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <label><?php echo $form->get('obs')->getLabel(); ?></label>
            <?php echo $this->formElement($form->get('obs')); ?>
        </div>
    </div>
    <div class="col-sm-1">
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
    <div class="col-sm-1">
        <div class="form-group">
            <?php echo $this->formReset($form->get('my-reset')); ?>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag();

