<?php

$title = 'Lista de Clientes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('cliente', array('action'=>'add'));?>"><button type="button" class="btn btn-default btn-sm">Adicionar Cliente</button></a>
</p>

<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Cliente</th>
            <th>Telefone</th>
            <th>E-mail</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($clientes as $cliente) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($cliente->id);?></td>
            <td><?php echo $this->escapeHtml($cliente->cliente);?></td>
            <td><?php echo $this->escapeHtml($cliente->telefone);?></td>
            <td><?php echo $this->escapeHtml($cliente->email);?></td>
            <td>
                <a href="<?php echo $this->url('cliente',
                    array('action'=>'edit', 'id' => $cliente->id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    &nbsp;&nbsp;
                <a href="<?php echo $this->url('cliente',
                    array('action'=>'delete', 'id' => $cliente->id));?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    &nbsp;&nbsp;
                <a href="#" onclick="verCliente(<?=$cliente->id?>)"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<!-- Modal ver cliente-->
<div class="modal fade bs-example-modal-sm" id="modalVerCliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Visualizar Cliente</h4>
      </div>
      <div class="modal-body" id="conteudoModal">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>