
<table class="table">
    <tr>
        <td>ID</td>
        <td><?php echo $this->escapeHtml($clientes->id);?></td>
    </tr>
    <tr>
        <td>Cliente</td>
        <td><?php echo $this->escapeHtml($clientes->cliente);?></td>
    </tr>
    <tr>
        <td>Telefone</td>
        <td><?php echo $this->escapeHtml($clientes->telefone);?></td>
    </tr>
    <tr>
        <td>E-mail</td>
        <td><?php echo $this->escapeHtml($clientes->email);?></td>
    </tr>
    <tr>
        <td>Data Nascimento</td>
        <td><?php echo $this->escapeHtml(date('d/m/Y', strtotime($clientes->dataNascimento)));?></td>
    </tr>
    <tr>
        <td>CPF</td>
        <td><?php echo $this->escapeHtml($clientes->cpf);?></td>
    </tr>
    <tr>
        <td>Observações</td>
        <td><?php echo $this->escapeHtml($clientes->obs);?></td>
    </tr>
</table>
